#!/usr/bin/env python3
"""Adapter: an AHE harness -> a HarnessGrad harness directory.

AHE is the sixth shape, and it is the first one that is **declarations rather than
code**.

  * The artifact is a directory of component files at fixed mount points. AHE's
    paper names seven types, and the seed harness
    (`agents/code_agent_simple/`) has one file or directory for each:

        system_prompt        systemprompt.md
        tool description     tool_descriptions/run_shell_command.tool.yaml
        tool implementation  tools/
        skill                (none in the seed)
        sub-agent config     (none in the seed)
        long-term memory     LongTermMEMORY.md
        middleware           (none in the seed)

  * Nothing in the directory executes on its own. `start.py` shows what runs
    instead: `AgentConfig.from_yaml(...)` then `Agent(config=config)` from the
    **NexAU** framework, which is a dependency, not part of the artifact. So the
    harness is a *configuration* for an engine the method supplies.

Why this tests the platform's spec: the platform's unit is "a directory with an
entrypoint that solves a task". AHE's unit is "a directory of declarations for
someone else's engine". The adapter bridges that by generating one entrypoint that
loads the declarations and drives NexAU -- adding no capability, because anything
it added would be an edit the platform made to someone else's harness.

The editable surface is the whole configuration directory, which is what AHE
itself treats as the harness; `init_workspace` (`evolve.py:306`) copies exactly
this directory into a workspace for the evolve agent.

Usage:
    python adapters/ahe.py --repo <ahe> --out-dir <dir>
    python adapters/ahe.py --repo <ahe> --trajectory --out trajectory.json
"""
from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

SEED = "agents/code_agent_simple"

#: The seven component types AHE's paper names, and where the seed harness keeps
#: each. Recorded rather than discovered, because "which files are the harness" is
#: a claim the method makes and the platform should carry it verbatim.
COMPONENT_MAP = {
    "system_prompt": "systemprompt.md",
    "tool_description": "tool_descriptions/",
    "tool_implementation": "tools/",
    "middleware": None,
    "skill": None,
    "subagent": None,
    "long_term_memory": "LongTermMEMORY.md",
}

ENTRYPOINT = '''#!/usr/bin/env python3
"""Generated by HarnessGrad's AHE adapter. Loads AHE's component declarations and
drives NexAU. Adds no capability -- a seam, not an edit."""
import argparse, json, os, sys
from datetime import datetime
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from nexau import Agent, AgentConfig


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--task", required=True)
    ap.add_argument("--workdir", required=True)
    args = ap.parse_args()

    task = json.loads(Path(args.task).read_text())
    workdir = Path(args.workdir)

    config = AgentConfig.from_yaml(config_path=HERE / "code_agent.yaml")
    agent = Agent(config=config)

    context = {{
        "date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "username": os.getenv("USER"),
        "working_directory": str(workdir),
    }}
    response = agent.run(message=task["goal"], context=context)
    (workdir / "answer.txt").write_text(str(response))
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''

MANIFEST = {
    "name": "ahe-harness",
    "version": "0.1.0",
    "path": ".",
    "entrypoint": "agent.py",
    "backend": "cli",
    # Null, not a filename: the EntryPoint needs `nexau`, whose dependencies live
    # in AHE's own pyproject.toml, not in anything this adapter could write. A
    # manifest that names an install file it does not ship is a claim the
    # validator catches -- which it did, on the first run of this adapter, and
    # that is the validator earning its place.
    "install": None,
}


def compile_harness(repo: Path, dest: Path) -> dict:
    seed = repo / SEED
    if not seed.is_dir():
        raise SystemExit(f"no AHE seed harness at {seed}")

    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)

    # The declarations ARE the harness, so they are copied whole. `start.py` is
    # excluded: it is a manual test driver that reads from stdin, not part of what
    # the evolve agent edits.
    for item in seed.iterdir():
        if item.name in ("start.py", ".gitignore"):
            continue
        if item.is_dir():
            shutil.copytree(item, dest / item.name)
        else:
            shutil.copy2(item, dest / item.name)

    (dest / "harness.json").write_text(json.dumps(MANIFEST, indent=2) + "\n")
    (dest / "agent.py").write_text(ENTRYPOINT)

    present = {k: v for k, v in COMPONENT_MAP.items() if v and (dest / v).exists()}
    absent = [k for k, v in COMPONENT_MAP.items() if not v or not (dest / v).exists()]

    return {
        "harness_dir": str(dest),
        "components_present": sorted(present),
        "components_absent": sorted(absent),
        "files": sorted(str(p.relative_to(dest)) for p in dest.rglob("*")
                        if p.is_file()),
    }


def to_trajectory(repo: Path, out_dir: Path) -> dict:
    """One step: the seed harness as AHE ships it.

    AHE's own runs are not shipped with the repository, so there is no second
    state to show. Reporting one honest step is the right answer; inventing an
    "evolved" state would be fabricating a trajectory.
    """
    compiled = compile_harness(repo, out_dir / "seed")
    step = {
        "harness_dir": compiled["harness_dir"],
        "label": "AHE seed harness (NexAU0: one shell tool, no middleware)",
        "edit_kind": "harness_config",
        "claimed_cost": {
            "note": "AHE reports wall-clock only (~32 hours for a 10-iteration "
                    "run); no token or dollar cost",
        },
        "method_reported": {
            "score": None,
            "score_provenance": "not reported (no run was executed)",
            "components_present": compiled["components_present"],
            "components_absent": compiled["components_absent"],
            "materializable": True,
            "measurable_by_platform": None,
            "measurable_note": (
                "the declarations are real and compile into a directory the "
                "platform can validate, but running them needs the NexAU engine "
                "and LLM_* environment variables, which are the method's"
            ),
        },
    }
    return {
        "steps": [step],
        "nominated": 0,
        "trajectory_shape": "sequence",
        "curve_drawn": "per_committed_harness",
        "rhythm": {
            "note": "AHE owns its loop: 10 iterations, k=2, one shared workspace "
                    "for all train tasks",
        },
        "selected_on_reported_set": None,
        "selection_pool_size": 1,
        "provenance": {
            "method": "AHE (Agentic Harness Engineering)",
            "source": "china-qijizhifeng/agentic-harness-engineering",
            "acceptance_rule": {
                # 这里原本写的是"PASS@1 高过历史最好就保留 (Algorithm 1 line 14)",
                # 并把来源标成 `evolve.py, ahe.txt:287-306`。两处都错了:AHE 的检出里
                # **没有任何 .txt 文件**,而 `evolve.py` 的循环里**根本没有接受判定** ——
                # 每轮结束后 evolve agent 的工作区被直接带进下一轮,全局唯一的
                # `perform_auto_rollback` 只在 resume 时调用。
                #
                # 唯一量化的判定是**归因**,不是门:`evaluate_changes` 拿上一轮预先声明的
                # predicted_fixes/risk_tasks 与实际翻转对照,给出
                # HARMFUL/MIXED/EFFECTIVE/PARTIALLY_EFFECTIVE/INEFFECTIVE,写进下一轮
                # 的 prompt,由**模型自己**决定要不要回滚。把"有归因"写成"有接受门",
                # 会让这个方法的可观测性听起来像一道它并不存在的保险。
                "text": "none: AHE carries the evolve agent's workspace forward after "
                        "every iteration. Its one quantitative rule is attribution, not "
                        "acceptance -- pre-declared predicted_fixes/risk_tasks are "
                        "graded against observed flips and the verdict is rendered into "
                        "the next prompt, where the *model* decides whether to roll back",
                "source": "evolve.py:2239-2329 (attribution verdicts); "
                          "evolve.py:4244 (the loop's only break is target_pass_rate); "
                          "no acceptance branch exists",
                "calibrated": False,
            },
            "editable_surface": {
                "declared_editable": sorted(v for v in COMPONENT_MAP.values() if v),
                "declared_in": "the paper's seven component types, at fixed mount "
                               "points; init_workspace (evolve.py:306) copies the "
                               "whole configuration directory",
                "search_parameters_editable_by_search": False,
                "evidence": (
                    "the step budget and per-task timeout are fitted to one model "
                    "and live in the run configuration, outside the workspace the "
                    "evolve agent edits -- AHE's own limitations note this and "
                    "call the coupling a generalization hazard"
                ),
            },
        },
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True)
    ap.add_argument("--out-dir", default=None)
    ap.add_argument("--trajectory", action="store_true")
    ap.add_argument("--out", default="trajectory.json")
    args = ap.parse_args()

    repo = Path(args.repo)
    if args.trajectory:
        out_dir = Path(args.out).parent / "ahe_states"
        traj = to_trajectory(repo, out_dir)
        Path(args.out).write_text(json.dumps(traj, indent=1))
        s = traj["steps"][0]["method_reported"]
        print(f"1 step -> {args.out}")
        print(f"  components present: {s['components_present']}")
        print(f"  components absent : {s['components_absent']}")
        return 0

    dest = Path(args.out_dir or "/tmp/hg-ahe")
    info = compile_harness(repo, dest)
    print(f"compiled -> {info['harness_dir']}")
    print(f"  present: {info['components_present']}")
    print(f"  absent : {info['components_absent']}")
    print(f"  files  : {len(info['files'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
