#!/usr/bin/env python3
"""Adapter: a HarnessX harness -> a HarnessGrad harness directory.

HarnessX is the eighth shape, and structurally it is the closest of the eight to
what this project means by a harness.

  * The artifact is **a YAML file**. `HarnessConfig`
    (`harnessx/core/harness.py:744`) is *"pure behaviour pipeline … defines what
    the agent does (processors, tools, workspace, tracer) but carries no model
    information"*, and `examples/minimal/harness_config.yaml` is the whole of a
    harness: a label, a description, and `processors: []`.
  * The model is **deliberately not part of it**. It is supplied at composition
    time: `model_config.agentic(harness_config)` → `await agent.run(task)`
    (`harnessx/core/model_config.py:73`). Composition is a separate class, and its
    docstring carries the warning once (`harnessx/core/harness.py:969-976`):
    *"Do not instantiate directly — use ModelConfig.agentic."*
  * Tools come from a registry built at runtime
    (`harnessx/tools/builtin/__init__.py:155`, `build_default_tools()`), not from
    the YAML — which the CLI shows: it builds the registry, converts it to config,
    and only then composes (`harnessx/cli.py:428-450`).

So this adapter compiles a config file plus a model config into a directory with an
entrypoint that composes them. Two notes that matter for the platform:

**The model is a composition input, not harness content.** That is a cleaner split
than any other method here has, and it means a HarnessX harness can be measured
under several models without being a different harness. The platform already keeps
`agent_model` on every curve point, so the distinction survives.

**The editable surface is the YAML, and it is thin.** A harness with
`processors: []` gives a method almost nothing to edit; the improvement space is in
the processor list, and every processor referenced there must exist in the
installed `harnessx` package. A method can therefore only compose *existing*
processors by editing the YAML, or add new ones by writing code — and those are two
different kinds of edit, which is exactly what `edit_kind` is for.

Usage:
    python adapters/harnessx.py --repo <harnessx> --example minimal --out-dir <dir>
    python adapters/harnessx.py --repo <harnessx> --trajectory --out trajectory.json
"""
from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

#: The five examples HarnessX ships. They differ only in their processor lists,
#: which makes them a natural set of states for one trajectory.
EXAMPLES = ("minimal", "coding", "assistant", "research", "custom_processor")

ENTRYPOINT = '''#!/usr/bin/env python3
"""Generated by HarnessGrad's HarnessX adapter. Composes a HarnessX
HarnessConfig with a ModelConfig and runs one task. Adds no capability."""
import argparse, asyncio, json, os, sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
# The `harnessx` package is the method's, not the platform's and not ours: it is
# the engine this config is a config FOR. Pointing at the method's checkout is the
# same move the TTHE adapter makes, and for the same reason -- the platform does
# not vendor other people's engines.
sys.path.insert(0, {repo!r})

from harnessx.core.harness import BaseTask, HarnessConfig
from harnessx.core.model_config import ModelConfig


async def _run(goal: str, max_steps: int) -> str:
    harness_config = HarnessConfig.from_yaml((HERE / "harness_config.yaml").read_text())

    model_path = Path(os.environ.get("HG_HARNESSX_MODEL_CONFIG",
                                     HERE / "model_config.yaml"))
    if not model_path.exists():
        raise SystemExit(
            f"no model config at {model_path}. HarnessX's harness carries no model "
            "information by design, so one must be supplied; set "
            "HG_HARNESSX_MODEL_CONFIG or place model_config.yaml beside this file."
        )
    model_config = ModelConfig.from_yaml_file(model_path)

    agent = model_config.agentic(harness_config)
    result = await agent.run(BaseTask(description=goal, max_steps=max_steps))
    # HarnessResult proxies unknown attributes to its TaskEndEvent, which is where
    # the final answer lives; fall back explicitly rather than guessing a name.
    for attr in ("final_answer", "answer", "output", "response", "content"):
        value = getattr(result, attr, None)
        if isinstance(value, str) and value.strip():
            return value
    return json.dumps({"note": "no string answer attribute on the result",
                       "attrs": [a for a in dir(result) if not a.startswith("_")][:40]})


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--task", required=True)
    ap.add_argument("--workdir", required=True)
    args = ap.parse_args()

    task = json.loads(Path(args.task).read_text())
    max_steps = int((task.get("inputs") or {}).get("max_steps", 30))
    answer = asyncio.run(_run(task["goal"], max_steps))
    (Path(args.workdir) / "answer.txt").write_text(str(answer))
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''

MODEL_TEMPLATE = """# HarnessX model config, supplied by whoever measures this harness.
#
# HarnessX keeps the model OUT of the harness on purpose: `HarnessConfig` carries
# no model information, and `model_config.agentic(harness_config)` joins the two.
# So this file is not part of the harness and a method does not edit it -- changing
# the model changes the measurement, not the artifact, and the platform records
# `agent_model` on every curve point for exactly that reason.
#
# Fill in a provider block and delete this comment. The `main` key is required.
main:
  provider: openai
  model: ${env:HG_AGENT_MODEL}
  base_url: ${env:HG_BASE_URL}
  api_key: ${env:HG_API_KEY}
"""

MANIFEST_TEMPLATE = {
    "name": "harnessx-harness",
    "version": "0.1.0",
    "path": ".",
    "entrypoint": "agent.py",
    "backend": "cli",
    # Null: the artifact needs the `harnessx` package itself, whose dependencies
    # live in HarnessX's pyproject.toml, not in anything this adapter writes.
    "install": None,
}


def compile_harness(repo: Path, example: str, dest: Path) -> dict:
    src = repo / "examples" / example / "harness_config.yaml"
    if not src.is_file():
        raise SystemExit(f"no such HarnessX example: {src}")

    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)

    # The harness itself: one YAML.
    shutil.copy2(src, dest / "harness_config.yaml")

    # Everything the example directory carries besides the config -- custom
    # processor code for the `custom_processor` example, for instance. That code
    # IS part of the harness, because the YAML references it.
    for item in (repo / "examples" / example).iterdir():
        if item.name in ("harness_config.yaml", "__pycache__"):
            continue
        if item.is_dir():
            shutil.copytree(item, dest / item.name,
                            ignore=shutil.ignore_patterns("__pycache__"))
        else:
            shutil.copy2(item, dest / item.name)

    # The model config is NOT copied from the method: it is ours to supply, and a
    # template is written so its absence is a clear, actionable state rather than
    # a mystery.
    (dest / "model_config.yaml").write_text(MODEL_TEMPLATE)

    manifest = dict(MANIFEST_TEMPLATE, name=f"harnessx-{example}")
    (dest / "harness.json").write_text(json.dumps(manifest, indent=2) + "\n")
    (dest / "agent.py").write_text(
        ENTRYPOINT.replace("{repo!r}", repr(str(repo.resolve()))))

    return {
        "harness_dir": str(dest),
        "example": example,
        "files": sorted(str(p.relative_to(dest)) for p in dest.rglob("*")
                        if p.is_file()),
    }


def _processor_count(path: Path) -> int | None:
    """How many processors the config declares.

    Read with an indentation-aware scan rather than a YAML dependency, because
    requiring one to *count* would be a reason this adapter fails on a host where
    the harness itself would have run fine. Nested blocks (a processor's own
    `memory:` config also contains `_target_` entries) are excluded by indentation:
    only list items directly under the top-level `processors:` key count.

    A naive `count(",")` scan reported 0 for every example including `coding`,
    whose pipeline is five processors long -- a reading that would have made five
    different harnesses look identical on the platform's axis.
    """
    try:
        lines = path.read_text().splitlines()
    except OSError:
        return None

    key_indent = None
    count = 0
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        indent = len(line) - len(line.lstrip())

        if key_indent is None:
            if stripped.startswith("processors:"):
                rest = stripped.split(":", 1)[1].strip()
                if rest == "[]":
                    return 0
                key_indent = indent
            continue

        # Inside the processors block: a top-level item is one indented deeper
        # than the key and begins with "- ".
        if indent <= key_indent:
            break
        if indent == key_indent + 2 and stripped.startswith("- "):
            count += 1
    return count if key_indent is not None else None


# Corrections (verified with `grep -rin` against methods_src/harnessx):
#   * "AEGIS" and "seesaw constraint" appear nowhere in the source; both were
#     removed from the provenance below.
#   * the shipping gate is not "in the CLI and the builder" -- it is
#     harnessx/meta_harness/validate_workflow.py (EvolveValidator) plus
#     harnessx/meta_harness/replay.py, and the acceptance gate is
#     recipe/{gaia,tau2}_evolver/run.py::_score_and_gate.
#   * "a single meta-agent over 15 rounds" was wrong twice: 15 is the TB2
#     training-set size, and the round counts in the source are 3 (default),
#     5 (published TB2 experiment) and 8 (all-domain GAIA runner).
def to_trajectory(repo: Path, out_dir: Path) -> dict:
    """Five steps, one per example HarnessX ships.

    Not a run: HarnessX's own evolution trajectories are not in the repository.
    What the examples give is a set of harnesses that differ in one visible way --
    how many processors they compose -- which is a real axis of this method and is
    worth putting on the platform's axis rather than inventing states.
    """
    steps = []
    for example in EXAMPLES:
        if not (repo / "examples" / example / "harness_config.yaml").is_file():
            continue
        c = compile_harness(repo, example, out_dir / example)
        steps.append({
            "harness_dir": c["harness_dir"],
            "label": f"HarnessX example: {example}",
            "edit_kind": "processor_pipeline",
            "claimed_cost": {
                "note": "HarnessX reports meta-agent tokens for its own runs; the "
                        "shipped examples carry none",
            },
            "method_reported": {
                "score": None,
                "score_provenance": "not reported (no run was executed)",
                "example": example,
                "processors": _processor_count(
                    repo / "examples" / example / "harness_config.yaml"),
                "materializable": True,
                "measurable_by_platform": None,
                "measurable_note": (
                    "the config composes into a real harness, but running it needs "
                    "the `harnessx` package and a model config; the model is a "
                    "composition input by design, not harness content"
                ),
            },
        })

    return {
        "steps": steps,
        "nominated": len(steps) - 1,
        "trajectory_shape": "sequence",
        "curve_drawn": "per_example_harness",
        "rhythm": {
            # Corrected: 15 is the TB2 *training-set* size
            # (recipe/tb2_evolver/README.md:54,120), not a round count. The round
            # counts in the source are 3 by default (gaia_evolver/defaults.py:26,
            # tau2_evolver/defaults.py:31), 5 in the published TB2 experiment
            # (tb2_evolver/README.md:124-126), and 8 for the all-domain GAIA runner
            # (gaia_evolver/run_meta.py:78).
            "note": "HarnessX owns its loop: one meta-agent (MetaAgent.evolve) per "
                    "round, 3 rounds by default, over a deterministic shipping gate",
        },
        "selected_on_reported_set": None,
        "selection_pool_size": len(steps),
        "provenance": {
            "method": "HarnessX",
            "source": "darwin-agent/HarnessX",
            "acceptance_rule": {
                # Corrected: "AEGIS", "reputation rule" and "Critic" appear nowhere
                # in the source (`grep -rin` over methods_src/harnessx). What the
                # code has is a best-so-far gate over pass_rate minus a cost penalty,
                # with an absolute passed-count noise guard on rollback.
                "text": "the meta-agent's proposed config ships only if the "
                        "post-flight validator accepts it (canonicalize + hook "
                        "contract + synthetic-task replay, then novelty/evidence) "
                        "and the round beats the historical best under "
                        "score = pass_rate - cost_weight*max(cost_delta_ratio,0), "
                        "with a passed-count noise guard on rollback",
                "source": "harnessx/meta_harness/validate_workflow.py "
                          "(EvolveValidator) + harnessx/meta_harness/replay.py; "
                          "recipe/gaia_evolver/run.py::_score_and_gate",
                "calibrated": False,
            },
            "editable_surface": {
                "declared_editable": ["harness_config.yaml", "the example's own code"],
                "declared_in": "HarnessConfig (harnessx/core/harness.py:744) -- "
                               "processors, tools, workspace, tracer",
                "search_parameters_editable_by_search": False,
                "evidence": (
                    # Corrected: the gate is not in the CLI/builder and there is no
                    # "seesaw constraint" (grep found neither phrase). It lives in
                    # meta_harness/validate_workflow.py + replay.py, outside the
                    # config a method edits. The claim that the paper reports no
                    # held-out evaluation was also wrong -- the TB2 README reports an
                    # unseen-task split (recipe/tb2_evolver/README.md:97-110).
                    "the shipping gate (canonicalize + hook contract + synthetic-"
                    "task replay, then novelty/evidence policy, then a non-blocking "
                    "literals advisory) is in harnessx/meta_harness/, outside the "
                    "config a method edits; the round still has to beat the "
                    "historical best at the recipe's own gate"
                ),
            },
            "model_is_a_composition_input": True,
        },
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True)
    ap.add_argument("--example", default="minimal")
    ap.add_argument("--out-dir", default=None)
    ap.add_argument("--trajectory", action="store_true")
    ap.add_argument("--out", default="trajectory.json")
    args = ap.parse_args()

    repo = Path(args.repo)
    if args.trajectory:
        out_dir = Path(args.out).parent / "harnessx_states"
        traj = to_trajectory(repo, out_dir)
        Path(args.out).write_text(json.dumps(traj, indent=1))
        print(f"{len(traj['steps'])} step(s) -> {args.out}")
        for s in traj["steps"]:
            print(f"  {s['label']:38} processors={s['method_reported']['processors']}")
        return 0

    dest = Path(args.out_dir or f"/tmp/hg-harnessx-{args.example}")
    info = compile_harness(repo, args.example, dest)
    print(f"compiled -> {info['harness_dir']}")
    print(f"  files: {len(info['files'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
