#!/usr/bin/env python3
"""Adapter: a MAC artifact -> a HarnessGrad harness directory.

MAC is the seventh shape, and it is the first **method that is itself a platform**.
It ships an evaluation API, a sandbox, a cryptographic held-out split
(`X-Verifier-Secret`, injected into the agent container only after development
ends), a 12/24-hour budget, rate limiting and a usage meter. In structure that is
the same kind of thing as this project, aimed at a different question: MAC asks
*how well do frontier LLMs program an agent*, this platform asks *what did a
method's edits actually produce*.

What MAC produces is **an agent**, delivered as a single Python file that
`load_agent_class` (`eval_utils/agent_runner.py:49`) imports dynamically and
instantiates. So the artifact maps onto the platform's unit the same way TTHE's
does -- a class, not a program -- with a different interface:

    aime-meta-agent/tools/base_agent.py:106   class BaseAIMEAgent(ABC)
    :72    Problem(idx: int, question: str)
    :86    Prediction(idx: int, pred: str)
    :168   solve(problems: List[Problem], timeout_sec: int) -> List[Prediction]

The adapter compiles a solution file into a directory whose entrypoint converts one
platform task into one `Problem`, calls `solve`, and writes the `Prediction`. It
adds no capability.

**The thing worth noticing about MAC for this project:** its evaluation discipline
belongs to the *artifact's own benchmark*, not to the harness it evolves. Its
held-out split, its budget and its rate limits live in MAC's runner and API, and
none of them travel with the compiled agent. A platform that re-measures the
compiled agent is therefore measuring something MAC never reported: the same
artifact against a different task set, with a different budget, no verifier
secret, and no rate limit. That is not a flaw in either system; it is what
cross-platform measurement means, and it is why the curve point records who
measured the number.

Usage:
    python adapters/mac.py --repo <mac> --solution solution/baseline_thinking_agent.py \
        --out-dir <dir>
    python adapters/mac.py --repo <mac> --trajectory --out trajectory.json
"""
from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

DOMAIN = "aime-meta-agent"
DEFAULT_SOLUTION = "solution/baseline_thinking_agent.py"

#: MAC's evaluation discipline, recorded because it does NOT travel with the
#: compiled artifact. A consumer comparing this method's numbers with another
#: method's needs to know which of these were in force.
EVAL_DISCIPLINE = {
    "held_out_split": "cryptographic (X-Verifier-Secret injected after development)",
    "budget": "43,200 s (12 h); 86,400 s (24 h) for SWE-Bench and Terminal-Bench",
    "search_quota": "2,500 API calls per phase",
    "rate_limit": "enforced by the method's ModelProxy (rpm/tpm)",
    "reported_variance": "mean ± std over 3 runs; 33% of configurations have sd > 0.1",
    "travels_with_artifact": False,
}

ENTRYPOINT = '''#!/usr/bin/env python3
"""Generated by HarnessGrad's MAC adapter. Converts a platform task into a MAC
Problem, calls the artifact's solve(), writes the Prediction. Adds no capability."""
import argparse, importlib.util, json, sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE / "tools"))

from base_agent import Problem          # MAC's own data type


def _load_agent_class(path: Path):
    """Same discovery rule as MAC's `load_agent_class` (agent_runner.py:49):
    the first BaseAIMEAgent subclass defined in the file."""
    from base_agent import BaseAIMEAgent
    spec = importlib.util.spec_from_file_location("mac_artifact", path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules["mac_artifact"] = mod
    spec.loader.exec_module(mod)
    for obj in vars(mod).values():
        if (isinstance(obj, type) and issubclass(obj, BaseAIMEAgent)
                and obj is not BaseAIMEAgent):
            return obj
    raise SystemExit("no BaseAIMEAgent subclass found in the artifact")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--task", required=True)
    ap.add_argument("--workdir", required=True)
    args = ap.parse_args()

    task = json.loads(Path(args.task).read_text())
    AgentClass = _load_agent_class(HERE / "artifact.py")
    agent = AgentClass()

    timeout = int((task.get("inputs") or {}).get("timeout_sec", 3600))
    preds = agent.solve([Problem(idx=0, question=task["goal"])], timeout_sec=timeout)

    answer = ""
    for p in preds or []:
        if getattr(p, "idx", 0) == 0:
            answer = getattr(p, "pred", "") or ""
            break
    (Path(args.workdir) / "answer.txt").write_text(str(answer))
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''

MANIFEST = {
    "name": "mac-artifact",
    "version": "0.1.0",
    "path": ".",
    "entrypoint": "agent.py",
    "backend": "cli",
    # Null: the artifact needs MAC's own `tools/` package and whatever the solution
    # imports. Those are the method's environment, and naming an install file this
    # adapter does not ship would be a claim the validator rejects.
    "install": None,
}


def compile_artifact(repo: Path, solution: str, dest: Path) -> dict:
    src = repo / DOMAIN / solution
    if not src.is_file():
        raise SystemExit(f"no such MAC artifact: {src}")

    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)

    # The artifact itself, under a fixed name the entrypoint can find.
    shutil.copy2(src, dest / "artifact.py")

    # MAC's `tools/` package: `base_agent.py` defines the interface the artifact
    # implements, and the artifact imports it. It is NOT part of the editable
    # surface in MAC -- the meta-agent writes a solution file, not the base class
    # -- so it is copied as a dependency.
    shutil.copytree(repo / DOMAIN / "tools", dest / "tools",
                    ignore=shutil.ignore_patterns("__pycache__"))

    (dest / "harness.json").write_text(json.dumps(MANIFEST, indent=2) + "\n")
    # Written verbatim: the template has no placeholders, so it is not passed
    # through .format() -- whose brace escaping turned `{}.get(...)` into a dict
    # literal and broke the entrypoint at runtime.
    (dest / "agent.py").write_text(ENTRYPOINT)

    return {
        "harness_dir": str(dest),
        "artifact": solution,
        "editable_surface": ["artifact.py"],
        "files": sorted(str(p.relative_to(dest)) for p in dest.rglob("*")
                        if p.is_file()),
    }


def to_trajectory(repo: Path, out_dir: Path) -> dict:
    """Two artifacts, both shipped by MAC: the baseline and the oracle.

    MAC's own runs are not in the repository, so there is no meta-agent trajectory
    to show. Baseline and oracle are the two points MAC itself provides, and the
    gap between them is the headroom MAC's benchmark is built around.
    """
    steps = []
    for sol, label, kind in (
        (DEFAULT_SOLUTION, "MAC baseline agent (as shipped)", "artifact_source"),
        ("solution/oracle_agent.py", "MAC oracle agent (upper bound)", "artifact_source"),
    ):
        if not (repo / DOMAIN / sol).is_file():
            continue
        c = compile_artifact(repo, sol, out_dir / Path(sol).stem)
        steps.append({
            "harness_dir": c["harness_dir"],
            "label": label,
            "edit_kind": kind,
            "claimed_cost": {
                "note": "MAC meters target-agent resource use in its runner; that "
                        "metering does not travel with the compiled artifact",
            },
            "method_reported": {
                "score": None,
                "score_provenance": "not reported (no run was executed)",
                "artifact": sol,
                "materializable": True,
                "measurable_by_platform": None,
                "measurable_note": (
                    "the artifact class and MAC's interface package are real and "
                    "compile, but running it needs the artifact's own model "
                    "endpoint and API key"
                ),
            },
        })

    return {
        "steps": steps,
        "nominated": 0,
        "trajectory_shape": "sequence",
        "curve_drawn": "per_artifact",
        "rhythm": {
            "note": "MAC owns its loop: a meta-agent programs an artifact inside a "
                    "sandbox with an evaluation API and a 12/24-hour budget",
        },
        "selected_on_reported_set": None,
        "selection_pool_size": len(steps),
        "provenance": {
            "method": "MAC (Meta-Agent Challenge)",
            "source": "ant-research/meta-agent-challenge",
            "acceptance_rule": {
                "text": "not applicable: MAC measures the optimizer, it does not "
                        "accept or reject harness edits",
                "source": "-",
                "calibrated": False,
            },
            "editable_surface": {
                "declared_editable": ["artifact.py"],
                "declared_in": "MAC's meta-agent writes a solution file; the base "
                               "class is the interface, not part of the submission",
                "search_parameters_editable_by_search": False,
                "evidence": (
                    "the meta-agent runs inside MAC's sandbox with MAC's runner; "
                    "the runner, the verifier secret and the budget are all outside "
                    "the artifact it writes"
                ),
            },
            "eval_discipline": EVAL_DISCIPLINE,
        },
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True)
    ap.add_argument("--solution", default=DEFAULT_SOLUTION)
    ap.add_argument("--out-dir", default=None)
    ap.add_argument("--trajectory", action="store_true")
    ap.add_argument("--out", default="trajectory.json")
    args = ap.parse_args()

    repo = Path(args.repo)
    if args.trajectory:
        out_dir = Path(args.out).parent / "mac_states"
        traj = to_trajectory(repo, out_dir)
        Path(args.out).write_text(json.dumps(traj, indent=1))
        print(f"{len(traj['steps'])} step(s) -> {args.out}")
        for s in traj["steps"]:
            print(f"  {s['label']:38} {s['method_reported']['artifact']}")
        return 0

    dest = Path(args.out_dir or "/tmp/hg-mac")
    info = compile_artifact(repo, args.solution, dest)
    print(f"compiled -> {info['harness_dir']}")
    print(f"  artifact : {info['artifact']}")
    print(f"  editable : {info['editable_surface']}")
    print(f"  files    : {len(info['files'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
