#!/usr/bin/env python3
"""Adapter: a TTHE harness -> a HarnessGrad harness directory.

TTHE's shape is unlike the other three, and the difference is worth stating
because it is the one the platform's own spec almost cannot express.

  * The artifact is **a Python class**, not a program. `text_to_sql/harness_base.py:20`
    defines `SQLHarness(ABC)` with one abstract method (`solve`) and a set of
    capabilities the subclass inherits (`llm`, `execute`, `tables`, ...). Its own
    docstring says the quiet part: *"Subclass this. You may rewrite ANY part of a
    harness -- control flow, prompts, number of solver …"*
  * There is no `harness.json`, no entrypoint, and no answer file. TTHE's runner
    instantiates the class itself (`text_to_sql/bt.py:133  bare = BareHarness(db)`)
    and calls `solve(question)`.

So this adapter is a **compiler**: it turns a class into a directory that
satisfies `docs/writing_a_harness.md`. That is the whole job, and doing it here
rather than asking TTHE to change is the platform's stated position -- a method is
measured as published, and re-wiring it to fit would change what is measured.

The generated entrypoint is small on purpose: it does not add capability, it only
connects. Anything it added would be an edit the platform made to someone else's
harness, which is exactly the line `INTERFACE.md` §4.3 draws.

Usage:
    python adapters/tthe.py --repo <tthe> --domain text_to_sql --harness react \
        --out-dir <dir>            # compile one harness
    python adapters/tthe.py --repo <tthe> --domain text_to_sql --trajectory \
        --out trajectory.json      # a two-step trajectory: bare, then react
"""
from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

ENTRYPOINT = '''#!/usr/bin/env python3
"""Generated by HarnessGrad's TTHE adapter. Connects a TTHE harness class to the
platform's task/answer contract. Adds no capability."""
import argparse, json, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, {repo!r})

from {module} import {cls}          # the harness under test
from {bridge} import get_db          # TTHE's own db resolver

HARNESS_CLASS = {cls}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--task", required=True)
    ap.add_argument("--workdir", required=True)
    args = ap.parse_args()

    task = json.loads(Path(args.task).read_text())
    db_id = (task.get("inputs") or {{}}).get("db_id")
    db = get_db(db_id) if db_id else None
    answer = HARNESS_CLASS(db).solve(task["goal"])
    (Path(args.workdir) / "answer.txt").write_text(str(answer))
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''

MANIFEST = {
    "name": "tthe-harness",
    "version": "0.1.0",
    "path": ".",
    "entrypoint": "agent.py",
    "backend": "cli",
    "install": None,
}


def compile_harness(repo: Path, domain: str, harness: str, dest: Path) -> dict:
    """Write a platform-readable harness directory for one TTHE harness file.

    The editable surface is what TTHE itself treats as the harness: the domain's
    `agents/` directory (its seed harnesses live there) plus `harness_base.py`,
    which every subclass may rewrite. The domain's `bridge.py` and `ase/` are NOT
    included: they are the execution substrate, and TTHE's own docstring draws the
    same line -- the harness is the strategy, not the database client.
    """
    src = repo / domain
    if not (src / "agents" / f"{harness}.py").is_file():
        raise SystemExit(f"no such TTHE harness: {src}/agents/{harness}.py")

    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)

    # 1. the harness class and everything a subclass may rewrite.
    #
    # The DOMAIN DIRECTORY NAME IS PART OF THE INTERFACE: `agents/react.py` does
    # `from ..harness_base import SQLHarness`, a relative import that only
    # resolves if the package is still called what it was. Flattening the tree
    # breaks the harness at import time -- and it breaks it in a way that scores
    # as a harness failure, i.e. as "this harness does not work", which is a
    # claim about someone else's code produced by our packaging choice.
    pkg = dest / domain
    shutil.copytree(src / "agents", pkg / "agents")
    shutil.copy2(src / "harness_base.py", pkg / "harness_base.py")
    (pkg / "__init__.py").write_text("")

    # 2. the manifest, so the platform can find and run it
    (dest / "harness.json").write_text(json.dumps(MANIFEST, indent=2) + "\n")

    # 3. the connecting entrypoint -- the only thing this adapter authors
    cls = harness.capitalize() + "Harness"
    module = f"{domain}.agents.{harness}"
    bridge = f"{domain}.bridge"
    (dest / "agent.py").write_text(ENTRYPOINT.format(
        repo=str(repo.resolve()), module=module, cls=cls, bridge=bridge))

    return {
        "harness_dir": str(dest),
        "harness_class": f"{module}.{cls}",
        "files": sorted(str(p.relative_to(dest)) for p in dest.rglob("*") if p.is_file()),
    }


def to_trajectory(repo: Path, domain: str, out_dir: Path) -> dict:
    """Two steps, which is what TTHE's own search produces at minimum: it starts
    from a seed harness and commits an evolved one.

    `bare` then `react` is not a reproduction of a TTHE run -- it is the smallest
    honest trajectory with the right shape, and the platform measures both ends.
    """
    steps = []
    for name in ("bare", "react"):
        compiled = compile_harness(repo, domain, name, out_dir / name)
        steps.append({
            "harness_dir": compiled["harness_dir"],
            "label": f"TTHE seed harness: {name}",
            "edit_kind": "harness_source",
            "claimed_cost": {
                "note": "TTHE reports no search cost; its paper reports none",
            },
            "method_reported": {
                "score": None,
                "score_provenance": "not reported (no run was executed)",
                "harness_class": compiled["harness_class"],
                "materializable": True,
                "measurable_by_platform": None,
                "measurable_note": (
                    "the harness class is real and compiled, but running it needs "
                    "TTHE's own domain bridge and a database; whether the platform "
                    "can measure it depends on a task set that supplies db_id"
                ),
            },
        })

    return {
        "steps": steps,
        "nominated": 1,
        "trajectory_shape": "sequence",
        "curve_drawn": "per_committed_harness",
        "rhythm": {
            "note": "TTHE owns its loop: G fixed branches x R rounds, one judge "
                    "commit per unlabeled batch. This trajectory shows two seed "
                    "harnesses rather than a run.",
        },
        "selected_on_reported_set": None,
        "selection_pool_size": len(steps),
        "provenance": {
            "method": "TTHE",
            "source": "junnie00/TTHE",
            "acceptance_rule": {
                "text": "an agentic judge commits one of the G round-R branches; "
                        "the paper reports the judge is measurably miscalibrated",
                "source": "text_to_sql/*_optimize.py",
                "calibrated": False,
            },
            "editable_surface": {
                "declared_editable": ["agents/", "harness_base.py"],
                "declared_in": "harness_base.py:20 docstring -- 'You may rewrite "
                               "ANY part of a harness'",
                "search_parameters_editable_by_search": True,
                "evidence": (
                    "the proposer edits harness source, and harness_base.py is "
                    "itself inside the editable set, so the interface the harness "
                    "must satisfy is editable too -- the method can move its own "
                    "boundary"
                ),
            },
        },
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True)
    ap.add_argument("--domain", default="text_to_sql")
    ap.add_argument("--harness", default="react")
    ap.add_argument("--out-dir", default=None)
    ap.add_argument("--trajectory", action="store_true")
    ap.add_argument("--out", default="trajectory.json")
    args = ap.parse_args()

    repo = Path(args.repo)
    if args.trajectory:
        out_dir = Path(args.out).parent / "tthe_states"
        traj = to_trajectory(repo, args.domain, out_dir)
        Path(args.out).write_text(json.dumps(traj, indent=1))
        print(f"{len(traj['steps'])} step(s) -> {args.out}")
        for s in traj["steps"]:
            print(f"  {s['label']:28} {len(s['method_reported']['harness_class'])} "
                  f"class={s['method_reported']['harness_class']}")
        return 0

    dest = Path(args.out_dir or f"/tmp/hg-tthe-{args.harness}")
    info = compile_harness(repo, args.domain, args.harness, dest)
    print(f"compiled -> {info['harness_dir']}")
    print(f"  class: {info['harness_class']}")
    print(f"  files: {len(info['files'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
